sudo: false
language: java

env:
  - VERSION="1.0.0"

matrix:
  include:
    if: tag IS blank
    env: VERSION_SUFFIX="-ci.${TRAVIS_BUILD_NUMBER}+${TRAVIS_BRANCH}"

before_script:
  - mvn versions:set -DnewVersion="${VERSION}${VERSION_SUFFIX}"
  - mvn versions:commit

script:
  - mvn package