sudo: false
language: java

env:
  - BASE_VERSION="1.0.0"

before_script:
  - mvn versions:set -DnewVersion="${BASE_VERSION}-ci.${TRAVIS_BUILD_NUMBER}+${TRAVIS_BRANCH}"
  - mvn versions:commit

script:
  - mvn package