sudo: false
language: java

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - VERSION="1.0.0"

matrix:
  include:
    - if: tag IS blank AND branch = master
      env: VERSION_SUFFIX="-ci.${TRAVIS_BUILD_NUMBER}"
    - if: tag IS blank AND NOT branch = master
      env: VERSION_SUFFIX="-ci.${TRAVIS_BUILD_NUMBER}+${TRAVIS_BRANCH}"

before_script:
  - mvn versions:set -DnewVersion="${VERSION}${VERSION_SUFFIX}"
  - mvn versions:commit

script:
  - mvn package

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/target/mibnavigator-*-bin.*"
  skip_cleanup: true
  on:
    tags: true