/**
 * MIB Navigator
 *
 * Copyright (C) 2010, Matt Hamilton <matthamilton@live.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */

import java.util.EventListener;

/**
 * This interface defines methods necessary for an object to receive data from a GetRequestWorker.
 */
public interface GetRequestListener extends EventListener
{
    /**
     * Updates the listener with host address related information.
     * 
     * @param addressString the String version of the host IP address
     * @param resolvedAddress the DNS resolved name of the host IP address
     */
    public void hostAddressResolved(String addressString, String resolvedAddress);
    
    /**
     * Updates the listener with GetRequest data.  
     * 
     * @param result a GetRequestResult containing an OID and its returned value
     */
    public void requestResultReceived(GetRequestResult result);

    /**
     * Notifies the listener that the worker has terminated. If the worker was sent an interrupt 
     * or the worker successfully completed data retrieval, an empty String will be returned.  
     * Exceptions in the worker will result in an error message.
     * 
     * @param statusMessage the String message generated by the GetRequestWorker upon termination
     */
    public void requestTerminated(String statusMessage);
}
